# -*- coding: utf-8 -*-
"""SLR_CMGGipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11DZ4syqmndwpki4bQFpmsTnlKklv0X-1
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from fractions import Fraction

data = {
    'Sales': [2, 4, 6, 8, 10, 12, 14, 16, 18],
    'Advertising': [1, 2, 3, 4, 5, 6, 7, 8, 9]
}
df = pd.DataFrame(data)

print("DataFrame:")
print(df)

def calculate_slr(data):

    sum_x = data['Advertising'].sum()
    sum_y = data['Sales'].sum()
    x2 = (data['Advertising'] ** 2).sum()
    xy = (data['Sales'] * data['Advertising']).sum()
    n = len(data)


    b0 = ((sum_y * x2) - (sum_x * xy)) / ((n * x2) - (sum_x ** 2))
    b1 = ((n * xy) - (sum_x * sum_y)) / ((n * x2) - (sum_x ** 2))

    return b0, b1

b0, b1 = calculate_slr(df)
print(f'b0: {b0}, b1: {b1}')

b0_round = round(b0)
b1_fraction = Fraction(b1).limit_denominator(10)
print(f'Función aproximada: y = {b0_round} + ({b1_fraction})x')

y_points = np.array(data['Sales'])
x_points = np.array(data['Advertising'])

x_range = np.linspace(min(x_points) - 1, max(x_points) + 1, 100)

y_range = b0 + b1 * x_range

plt.plot(x_range, y_range, label=f'y = {b0_round} + ({b1_fraction})x', color='black')
plt.scatter(x_points, y_points, color='red', label='Datos')
plt.xlabel('Advertising')
plt.ylabel('Sales')
plt.title('SLR')
plt.legend(loc='upper left')
plt.grid(True)
plt.show()